In [1]:
import pandas as pd

train_data = pd.read_csv('C:/Users/jimin.DESKTOP-8V20QSQ/Desktop/user_spec_train.csv')
test_data = pd.read_csv('C:/Users/jimin.DESKTOP-8V20QSQ/Desktop/user_spec_test.csv')

In [3]:
train_data.head()

,application_id,loan_limit,loan_rate,is_applied,loan_limit_min/ loan_limit,user_id,insert_time,gender,score_type,age_cat,...,purpose_자동차구입,purpose_전월세보증금,purpose_주택구입,purpose_투자,PrepayCalc_freq,DSRCalc_freq,loan_freq,loan_limit / desired_amount,loan_rate_type_저,loan_rate_type_중
0,2157865,20000000.0,16.5,1.0,0.090909,346970,2022-05-09 08:44:57,1.0,8,50.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2.000,0,1
1,576643,11000000.0,16.5,0.0,0.090909,545882,2022-05-09 10:54:51,1.0,8,40.0,...,0.0,0.0,0.0,0.0,0.0,0.0,32,0.550,0,1
2,576643,3000000.0,20.0,0.0,0.075000,545882,2022-05-09 10:54:51,1.0,8,40.0,...,0.0,0.0,0.0,0.0,0.0,0.0,32,0.150,0,1
3,2136706,10000000.0,13.5,0.0,0.111111,558819,2022-05-09 10:41:05,1.0,6,30.0,...,0.0,0.0,0.0,0.0,0.0,0.0,119,0.125,0,1
4,2136706,22000000.0,15.9,0.0,0.094340,558819,2022-05-09 10:41:05,1.0,6,30.0,...,0.0,0.0,0.0,0.0,0.0,0.0,119,0.275,0,1

In [4]:
test_data.head()

,application_id,loan_limit,loan_rate,is_applied,loan_limit_min/ loan_limit,user_id,insert_time,gender,score_type,age_cat,...,purpose_자동차구입,purpose_전월세보증금,purpose_주택구입,purpose_투자,PrepayCalc_freq,DSRCalc_freq,loan_freq,loan_limit / desired_amount,loan_rate_type_저,loan_rate_type_중
0,1748340,42000000.0,13.6,NaN,0.235294,430982,2022-06-07 13:05:39,1.0,7,20.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,1.68,0,1
1,1748340,24000000.0,17.9,NaN,0.178771,430982,2022-06-07 13:05:39,1.0,7,20.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0.96,0,1
2,1748340,24000000.0,18.5,NaN,0.172973,430982,2022-06-07 13:05:39,1.0,7,20.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0.96,0,1
3,1748340,29000000.0,10.8,NaN,0.296296,430982,2022-06-07 13:05:39,1.0,7,20.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,1.16,0,1
4,1748340,5000000.0,16.4,NaN,0.195122,430982,2022-06-07 13:05:39,1.0,7,20.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0.20,0,1

In [27]:
train_data.describe()

,application_id,loan_limit,loan_rate,loan_limit_min/ loan_limit,user_id,gender,score_type,age_cat,yearly_income,work_year,...,purpose_전월세보증금,purpose_주택구입,purpose_투자,PrepayCalc_freq,DSRCalc_freq,loan_freq,loan_limit / desired_amount,loan_rate_type_저,loan_rate_type_중,is_applied
count,1.017278e+07,1.017278e+07,1.017278e+07,1.017278e+07,1.017278e+07,1.017278e+07,1.017278e+07,1.017278e+07,1.017278e+07,1.017278e+07,...,1.017278e+07,1.017278e+07,1.017278e+07,1.017278e+07,1.017278e+07,1.017278e+07,10172783.00,1.017278e+07,1.017278e+07,1.017278e+07
mean,1.083371e+06,2.259878e+07,1.277057e+01,1.323030e-01,4.402178e+05,6.937260e-01,5.082924e+00,3.476435e+01,4.790971e+07,4.298079e+00,...,4.308880e-02,4.295157e-02,2.181694e-02,3.852083e-02,2.561855e-02,1.698607e+02,inf,1.019701e-02,9.898030e-01,5.407753e-02
std,6.257491e+05,2.233100e+07,3.884854e+00,5.285511e-02,2.538027e+05,4.609450e-01,2.305836e+00,1.017824e+01,1.312376e+08,5.362023e+00,...,2.030570e-01,2.027480e-01,1.460855e-01,4.703410e-01,3.038466e-01,2.698850e+02,NaN,1.004641e-01,1.004641e-01,2.261706e-01
min,1.000000e+00,0.000000e+00,1.500000e+00,7.500000e-02,9.000000e+00,0.000000e+00,1.000000e+00,1.000000e+01,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.00,0.000000e+00,0.000000e+00,0.000000e+00
25%,5.419640e+05,9.000000e+06,9.500000e+00,9.493671e-02,2.212630e+05,0.000000e+00,3.000000e+00,3.000000e+01,2.900000e+07,1.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.300000e+01,0.30,0.000000e+00,1.000000e+00,0.000000e+00
50%,1.083692e+06,1.800000e+07,1.320000e+01,1.136364e-01,4.403010e+05,1.000000e+00,6.000000e+00,3.000000e+01,3.600000e+07,2.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.800000e+01,0.72,0.000000e+00,1.000000e+00,0.000000e+00
75%,1.624714e+06,3.300000e+07,1.580000e+01,1.578947e-01,6.610650e+05,1.000000e+00,7.000000e+00,4.000000e+01,5.000000e+07,5.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.910000e+02,1.60,0.000000e+00,1.000000e+00,0.000000e+00
max,2.167826e+06,1.000000e+10,2.000000e+01,1.000000e+00,8.796970e+05,1.000000e+00,1.000000e+01,9.000000e+01,1.000000e+10,1.110000e+02,...,1.000000e+00,1.000000e+00,1.000000e+00,2.500000e+01,2.200000e+01,4.493000e+03,inf,1.000000e+00,1.000000e+00,1.000000e+00

In [60]:
train_data[train_data['loan_limit / desired_amount'] == np.inf]

,loan_limit,loan_rate,loan_limit_min/ loan_limit,gender,score_type,age_cat,yearly_income,work_year,desired_amount,existing_loan_cnt,...,purpose_전월세보증금,purpose_주택구입,purpose_투자,PrepayCalc_freq,DSRCalc_freq,loan_freq,loan_limit / desired_amount,loan_rate_type_저,loan_rate_type_중,is_applied
44442,13000000.0,17.7,0.084746,1.0,7,30.0,16000000.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,214,inf,0,1,0.0
44443,2000000.0,19.9,0.075377,1.0,7,30.0,16000000.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,214,inf,0,1,0.0
44444,10000000.0,16.3,0.092025,1.0,7,30.0,16000000.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,214,inf,0,1,0.0
44445,4000000.0,19.9,0.075377,1.0,7,30.0,16000000.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,214,inf,0,1,0.0
44446,14000000.0,15.9,0.094340,1.0,7,30.0,16000000.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,214,inf,0,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10170052,11000000.0,6.8,0.220588,0.0,8,50.0,12000000.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,9,inf,0,1,1.0
10170053,11000000.0,7.4,0.202703,0.0,8,50.0,12000000.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,9,inf,0,1,0.0
10170054,11000000.0,7.8,0.192308,0.0,8,50.0,12000000.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,9,inf,0,1,0.0
10170055,10000000.0,9.4,0.159574,0.0,8,50.0,12000000.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,9,inf,0,1,0.0
10170056,11000000.0,7.0,0.214286,0.0,8,50.0,12000000.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,9,inf,0,1,0.0

In [2]:
is_applied = train_data['is_applied']
del train_data['is_applied']
train_data['is_applied'] = is_applied

In [3]:
is_applied = test_data['is_applied']
del test_data['is_applied']
test_data['is_applied'] = is_applied

In [4]:
del test_data['insert_time']
del train_data['insert_time']
del test_data['application_id']
del train_data['application_id']
del test_data['user_id']
del train_data['user_id']

In [5]:
del test_data['loan_limit / desired_amount']
del train_data['loan_limit / desired_amount']

In [9]:
x_train = train_data.iloc[:, :-1]
y_train = train_data.iloc[:, -1]

#print(x_train.shape, y_train.shape)

x_test = test_data.iloc[:, :-1]
y_test = test_data.iloc[:, -1]

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)

scaler.fit(x_test)
x_test = scaler.transform(x_test)

In [11]:
print(x_test.shape, y_test.shape)

(3219006, 34) (3219006,)

In [12]:
# training HyperParameters
learning_rate  = 0.001
batch_size     = 128
epochs         = 20

In [13]:
# build model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import RMSprop, SGD

model = Sequential()  # 선언
model.add(Dense(units = 64, activation='relu', input_shape=(34,)))   # neuron, input column개수
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))   # ouput column개수
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                2240

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 16)                528

 dense_3 (Dense)             (None, 1)                 17

=================================================================
Total params: 4,865
Trainable params: 4,865
Non-trainable params: 0
_________________________________________________________________

In [14]:
from sklearn.model_selection import train_test_split

x_train, x_valid, y_train, y_valid = train_test_split(x_train, y_train, test_size=0.2, shuffle=True, stratify=y_train)

In [15]:
model.compile(loss='binary_crossentropy',   
              optimizer='adam', 
              metrics=['accuracy'])

In [16]:
len(x_valid)

2034557

In [17]:
len(y_test)

3219006

In [18]:
history = model.fit(x_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=2,
                    validation_data=(x_valid, y_valid))

Epoch 1/20
63580/63580 - 118s - loss: 0.1640 - accuracy: 0.9460 - val_loss: 0.1604 - val_accuracy: 0.9460 - 118s/epoch - 2ms/step
Epoch 2/20
63580/63580 - 230s - loss: 0.1586 - accuracy: 0.9462 - val_loss: 0.1582 - val_accuracy: 0.9462 - 230s/epoch - 4ms/step
Epoch 3/20
63580/63580 - 210s - loss: 0.1570 - accuracy: 0.9463 - val_loss: 0.1569 - val_accuracy: 0.9464 - 210s/epoch - 3ms/step
Epoch 4/20
63580/63580 - 299s - loss: 0.1562 - accuracy: 0.9465 - val_loss: 0.1559 - val_accuracy: 0.9463 - 299s/epoch - 5ms/step
Epoch 5/20
63580/63580 - 232s - loss: 0.1557 - accuracy: 0.9465 - val_loss: 0.1558 - val_accuracy: 0.9465 - 232s/epoch - 4ms/step
Epoch 6/20

KeyboardInterrupt:

In [ ]:
# 5. 모델 학습 과정 표시하기
plt.plot(history.history['loss'],     label = 'train loss')
plt.plot(history.history['val_loss'], label = 'val loss')
plt.xlabel('the number of learning')
plt.ylabel('cost')
plt.legend()
plt.show()

In [ ]:
score = model.evaluate(x_train, y_train, verbose=0)
print('Train loss:',     score[0])
print('Train accuracy:', score[1])

score_test = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:',     score_test[0])
print('Test accuracy:', score_test[1])

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

# train
ypred_prob = model.predict(x_train)
ypred_int  = (model.predict(x_train) >= 0.5).astype(int)

print(confusion_matrix(y_train, ypred_int))
print(classification_report(y_train, ypred_int))
print('*'*50)

from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
print('Accuracy  = ', accuracy_score(y_train, ypred_int))
print('Precision = ', precision_score(y_train, ypred_int))
print('Recall    = ', recall_score(y_train, ypred_int))
print('F1        = ', f1_score(y_train, ypred_int))


# test
ypred_prob = model.predict(x_test)
ypred_int  = (model.predict(x_test) >= 0.5).astype(int)

print(confusion_matrix(y_test, ypred_int))
print(classification_report(y_test, ypred_int))
print('*'*50)

print('Accuracy  = ', accuracy_score(y_test, ypred_int))
print('Precision = ', precision_score(y_test, ypred_int))
print('Recall    = ', recall_score(y_test, ypred_int))
print('F1        = ', f1_score(y_test, ypred_int))

254320/254320 [==============================] - 793s 3ms/step
254320/254320 [==============================] - 884s 3ms/step
[[7676255   21876]
 [ 411836   28259]]
              precision    recall  f1-score   support

         0.0       0.95      1.00      0.97   7698131
         1.0       0.56      0.06      0.12    440095

    accuracy                           0.95   8138226
   macro avg       0.76      0.53      0.54   8138226
weighted avg       0.93      0.95      0.93   8138226

**************************************************
Accuracy  =  0.9467068130081421
Precision =  0.5636581230677171
Recall    =  0.06421113623194992
F1        =  0.11528874201905227
100594/100594 [==============================] - 348s 3ms/step
100594/100594 [==============================] - 393s 4ms/step